#!/usr/bin/env bash

# 設定ファイル名
printf "設定ファイル名を入力してください : "
read settings_file_name

if [[ -f $settings_file_name ]]; then
    echo "既にファイルが存在します。"
    echo -n "ファイルを削除してもよろしいですか？（y/N）"
    read yn
    case $yn in
        Y ) rm $settings_file_name;;
        y ) rm $settings_file_name;;
        Yes ) rm $settings_file_name;;
        yes ) rm $settings_file_name;;
        * ) :;;
    esac
fi

# 初期部分
cat << EOF >> $settings_file_name
#!/usr/bin/env bash
# Generated by generate_settings.bash

function settings () {
EOF

function add () {
    echo -en "$1"" : "
    read set_temp

    echo "    $2"="$set_temp" >> $settings_file_name
}

function add_array () {
    echo -en "$1"" : "
    read set_temp

    echo "    $2"="(""$set_temp"")" >> $settings_file_name
}

# add [メッセージ] [変数名]

# 設定開始
add "言語を入力してください" msg_language
add "作業ディレクトリを入力してください" working_directory
add "アーキテクチャを入力してください" make_arch
add "生成するイメージファイルのパスを入力してください"　image_file_path
add_array "追加するパッケージを入力してください" add_pkg
add "イメージファイルの所有ユーザーを入力してください" user
add "イメージファイルの所有グループを入力してください" group
add "イメージファイルのアクセス権限を入力してください" perm


# 終了部分
echo "}" >> $settings_file_name
chmod 750 $settings_file_name

./start_build.bash $settings_file_name
